image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки
  # - git config --global user.email "nikitakx9@gmail.com"
  # - git config --global user.name "nikitakozhukhar"
  # - git remote -v
  # - git branch -vv
  # - git status
  # - git push origin main

# test_script:
  # - npm run lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose